# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 656)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainLayout = QtWidgets.QGridLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.messageWidget = QtWidgets.QWidget(self.centralwidget)
        self.messageWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.messageWidget.setObjectName("messageWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.messageWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.messageLayout = QtWidgets.QGridLayout()
        self.messageLayout.setObjectName("messageLayout")
        self.messageHistoryLabel = QtWidgets.QLabel(self.messageWidget)
        self.messageHistoryLabel.setObjectName("messageHistoryLabel")
        self.messageLayout.addWidget(self.messageHistoryLabel, 0, 0, 1, 1)
        self.messageControlWidget = QtWidgets.QWidget(self.messageWidget)
        self.messageControlWidget.setObjectName("messageControlWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.messageControlWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.messageControlLayout = QtWidgets.QGridLayout()
        self.messageControlLayout.setVerticalSpacing(7)
        self.messageControlLayout.setObjectName("messageControlLayout")
        self.sendMessageButton = QtWidgets.QPushButton(self.messageControlWidget)
        self.sendMessageButton.setObjectName("sendMessageButton")
        self.messageControlLayout.addWidget(self.sendMessageButton, 0, 0, 1, 1)
        self.clearMessageButton = QtWidgets.QPushButton(self.messageControlWidget)
        self.clearMessageButton.setObjectName("clearMessageButton")
        self.messageControlLayout.addWidget(self.clearMessageButton, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.messageControlLayout)
        self.messageLayout.addWidget(self.messageControlWidget, 9, 0, 1, 1)
        self.messageHistoryEdit = QtWidgets.QTextEdit(self.messageWidget)
        self.messageHistoryEdit.setMinimumSize(QtCore.QSize(0, 300))
        self.messageHistoryEdit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.messageHistoryEdit.setReadOnly(True)
        self.messageHistoryEdit.setObjectName("messageHistoryEdit")
        self.messageLayout.addWidget(self.messageHistoryEdit, 2, 0, 1, 1)
        self.messageEdit = QtWidgets.QTextEdit(self.messageWidget)
        self.messageEdit.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.messageEdit.setFont(font)
        self.messageEdit.setStyleSheet("font-size: 10pt ;")
        self.messageEdit.setObjectName("messageEdit")
        self.messageLayout.addWidget(self.messageEdit, 4, 0, 1, 1)
        self.messageLabel = QtWidgets.QLabel(self.messageWidget)
        self.messageLabel.setObjectName("messageLabel")
        self.messageLayout.addWidget(self.messageLabel, 3, 0, 1, 1)
        self.buttons = QtWidgets.QHBoxLayout()
        self.buttons.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.buttons.setContentsMargins(0, 10, 200, -1)
        self.buttons.setSpacing(0)
        self.buttons.setObjectName("buttons")
        self.boldButton = QtWidgets.QPushButton(self.messageWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boldButton.sizePolicy().hasHeightForWidth())
        self.boldButton.setSizePolicy(sizePolicy)
        self.boldButton.setMinimumSize(QtCore.QSize(30, 30))
        self.boldButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.boldButton.setFont(font)
        self.boldButton.setObjectName("boldButton")
        self.buttons.addWidget(self.boldButton)
        self.italicButton = QtWidgets.QPushButton(self.messageWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.italicButton.sizePolicy().hasHeightForWidth())
        self.italicButton.setSizePolicy(sizePolicy)
        self.italicButton.setMinimumSize(QtCore.QSize(30, 30))
        self.italicButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.italicButton.setFont(font)
        self.italicButton.setObjectName("italicButton")
        self.buttons.addWidget(self.italicButton)
        self.underlinedButton = QtWidgets.QPushButton(self.messageWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.underlinedButton.sizePolicy().hasHeightForWidth())
        self.underlinedButton.setSizePolicy(sizePolicy)
        self.underlinedButton.setMinimumSize(QtCore.QSize(30, 30))
        self.underlinedButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.underlinedButton.setFont(font)
        self.underlinedButton.setObjectName("underlinedButton")
        self.buttons.addWidget(self.underlinedButton)
        self.smileButton = QtWidgets.QPushButton(self.messageWidget)
        self.smileButton.setMaximumSize(QtCore.QSize(30, 30))
        self.smileButton.setText("")
        self.smileButton.setObjectName("smileButton")
        self.buttons.addWidget(self.smileButton)
        self.smileButton_2 = QtWidgets.QPushButton(self.messageWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smileButton_2.sizePolicy().hasHeightForWidth())
        self.smileButton_2.setSizePolicy(sizePolicy)
        self.smileButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.smileButton_2.setText("")
        self.smileButton_2.setObjectName("smileButton_2")
        self.buttons.addWidget(self.smileButton_2)
        self.smileButton_3 = QtWidgets.QPushButton(self.messageWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smileButton_3.sizePolicy().hasHeightForWidth())
        self.smileButton_3.setSizePolicy(sizePolicy)
        self.smileButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.smileButton_3.setText("")
        self.smileButton_3.setObjectName("smileButton_3")
        self.buttons.addWidget(self.smileButton_3)
        self.fotoButton = QtWidgets.QPushButton(self.messageWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fotoButton.sizePolicy().hasHeightForWidth())
        self.fotoButton.setSizePolicy(sizePolicy)
        self.fotoButton.setMinimumSize(QtCore.QSize(30, 30))
        self.fotoButton.setMaximumSize(QtCore.QSize(30, 30))
        self.fotoButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.fotoButton.setStyleSheet("")
        self.fotoButton.setText("")
        self.fotoButton.setObjectName("fotoButton")
        self.buttons.addWidget(self.fotoButton)
        self.messageLayout.addLayout(self.buttons, 5, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.messageLayout)
        self.mainLayout.addWidget(self.messageWidget, 0, 1, 1, 1)
        self.contactsWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contactsWidget.sizePolicy().hasHeightForWidth())
        self.contactsWidget.setSizePolicy(sizePolicy)
        self.contactsWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.contactsWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.contactsWidget.setObjectName("contactsWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.contactsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contactsLayout = QtWidgets.QGridLayout()
        self.contactsLayout.setObjectName("contactsLayout")
        self.contactsLabel = QtWidgets.QLabel(self.contactsWidget)
        self.contactsLabel.setObjectName("contactsLabel")
        self.contactsLayout.addWidget(self.contactsLabel, 0, 0, 1, 2)
        self.contactsListView = QtWidgets.QListView(self.contactsWidget)
        self.contactsListView.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.contactsListView.setObjectName("contactsListView")
        self.contactsLayout.addWidget(self.contactsListView, 1, 0, 1, 1)
        self.contactsControlWidget = QtWidgets.QWidget(self.contactsWidget)
        self.contactsControlWidget.setObjectName("contactsControlWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.contactsControlWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.contactsControlLayout = QtWidgets.QGridLayout()
        self.contactsControlLayout.setObjectName("contactsControlLayout")
        self.addContactButton = QtWidgets.QPushButton(self.contactsControlWidget)
        self.addContactButton.setObjectName("addContactButton")
        self.contactsControlLayout.addWidget(self.addContactButton, 0, 1, 1, 1)
        self.remContactButton = QtWidgets.QPushButton(self.contactsControlWidget)
        self.remContactButton.setObjectName("remContactButton")
        self.contactsControlLayout.addWidget(self.remContactButton, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.contactsControlLayout)
        self.contactsLayout.addWidget(self.contactsControlWidget, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.contactsLayout)
        self.mainLayout.addWidget(self.contactsWidget, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.mainLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 26))
        self.menubar.setObjectName("menubar")
        self.menuContacts = QtWidgets.QMenu(self.menubar)
        self.menuContacts.setObjectName("menuContacts")
        self.menuAll_users = QtWidgets.QMenu(self.menubar)
        self.menuAll_users.setObjectName("menuAll_users")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_contact = QtWidgets.QAction(MainWindow)
        self.actionAdd_contact.setObjectName("actionAdd_contact")
        self.actionRemove_contact = QtWidgets.QAction(MainWindow)
        self.actionRemove_contact.setObjectName("actionRemove_contact")
        self.actionSearch = QtWidgets.QAction(MainWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.actionAll_users = QtWidgets.QAction(MainWindow)
        self.actionAll_users.setObjectName("actionAll_users")
        self.actionAll_contacts = QtWidgets.QAction(MainWindow)
        self.actionAll_contacts.setObjectName("actionAll_contacts")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuContacts.addAction(self.actionAdd_contact)
        self.menuContacts.addAction(self.actionRemove_contact)
        self.menuContacts.addAction(self.actionAll_contacts)
        self.menuAll_users.addAction(self.actionSearch)
        self.menuAll_users.addAction(self.actionAll_users)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuAll_users.menuAction())
        self.menubar.addAction(self.menuContacts.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.messageHistoryLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Message history</span></p></body></html>"))
        self.sendMessageButton.setText(_translate("MainWindow", "Send"))
        self.clearMessageButton.setText(_translate("MainWindow", "Clear"))
        self.messageLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Message</span></p></body></html>"))
        self.boldButton.setText(_translate("MainWindow", "B"))
        self.italicButton.setText(_translate("MainWindow", "I"))
        self.underlinedButton.setText(_translate("MainWindow", "U"))
        self.contactsLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Contacts</span></p></body></html>"))
        self.addContactButton.setText(_translate("MainWindow", "Add"))
        self.remContactButton.setText(_translate("MainWindow", "Remove"))
        self.menuContacts.setTitle(_translate("MainWindow", "Contacts"))
        self.menuAll_users.setTitle(_translate("MainWindow", "Users"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAdd_contact.setText(_translate("MainWindow", "Add contact"))
        self.actionRemove_contact.setText(_translate("MainWindow", "Remove contact"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))
        self.actionAll_users.setText(_translate("MainWindow", "All users"))
        self.actionAll_contacts.setText(_translate("MainWindow", "All contacts"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
